# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'guitar.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(784, 820)
        self.button_C = QtWidgets.QPushButton(Form)
        self.button_C.setGeometry(QtCore.QRect(90, 140, 93, 101))
        self.button_C.setStyleSheet("background-color:rgb(146, 190, 255)")
        self.button_C.setObjectName("button_C")
        self.button_D = QtWidgets.QPushButton(Form)
        self.button_D.setGeometry(QtCore.QRect(220, 140, 93, 101))
        self.button_D.setStyleSheet("background-color:rgb(146, 190, 255)")
        self.button_D.setObjectName("button_D")
        self.button_Em = QtWidgets.QPushButton(Form)
        self.button_Em.setGeometry(QtCore.QRect(360, 140, 93, 101))
        self.button_Em.setStyleSheet("background-color:rgb(146, 190, 255)")
        self.button_Em.setObjectName("button_Em")
        self.button_Bm7 = QtWidgets.QPushButton(Form)
        self.button_Bm7.setGeometry(QtCore.QRect(510, 140, 93, 101))
        self.button_Bm7.setStyleSheet("background-color:rgb(146, 190, 255)")
        self.button_Bm7.setObjectName("button_Bm7")
        self.button_G = QtWidgets.QPushButton(Form)
        self.button_G.setGeometry(QtCore.QRect(80, 280, 93, 101))
        self.button_G.setStyleSheet("background-color:rgb(146, 190, 255)")
        self.button_G.setObjectName("button_G")
        self.button_Am = QtWidgets.QPushButton(Form)
        self.button_Am.setGeometry(QtCore.QRect(220, 280, 93, 101))
        self.button_Am.setStyleSheet("background-color:rgb(146, 190, 255)")
        self.button_Am.setObjectName("button_Am")

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "TangYijun_guitar"))
        self.button_C.setText(_translate("Form", "C"))
        self.button_D.setText(_translate("Form", "D"))
        self.button_Em.setText(_translate("Form", "Em"))
        self.button_Bm7.setText(_translate("Form", "Bm"))
        self.button_G.setText(_translate("Form", "G"))
        self.button_Am.setText(_translate("Form", "Am"))
